"""complete dynamic time split slot tokens migration

Revision ID: 099fcdd410c7
Revises: 6cde85fd4e92
Create Date: 2026-06-24 00:08:21.217312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099fcdd410c7'
down_revision = '6cde85fd4e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 🚀 1. SAFELY HANDLE EXISTING DOCTOR_CONFIGS TABLE
    try:
        op.create_table('doctor_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('venue_address', sa.String(length=255), nullable=False),
        sa.Column('start_time', sa.String(length=5), nullable=False),
        sa.Column('end_time', sa.String(length=5), nullable=False),
        sa.Column('slot_duration_mins', sa.Integer(), nullable=False),
        sa.Column('fee', sa.Float(), nullable=False),
        sa.Column('work_on_sunday', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doctor_id')
        )
        print("Successfully created doctor_configs table.")
    except Exception as e:
        print("doctor_configs table already exists or skipping.")
        pass

    # 🚀 2. SAFELY HANDLE EXISTING DOCTOR_HOLIDAYS TABLE
    try:
        op.create_table('doctor_holidays',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_id', sa.Integer(), nullable=False),
        sa.Column('holiday_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        print("Successfully created doctor_holidays table.")
    except Exception as e:
        print("doctor_holidays table already exists or skipping.")
        pass
    
    # Redundant tables ko safely drop karne ke liye
    try: op.drop_table('venues') 
    except Exception: pass
    try: op.drop_table('old_appointments') 
    except Exception: pass
    try: op.drop_table('diagnostic_services') 
    except Exception: pass
    try: op.drop_table('medical_records') 
    except Exception: pass

    # 🚀 3. APPLY ALTERATION TO APPOINTMENTS TABLE
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'COMPLETED', 'APPROVE', 'REJECT', name='appointmentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIRMED'"))
        batch_op.alter_column('cancellation_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_appointments_slot_id', ['slot_id'])

    # 🚀 4. APPLY ALTERATION TO DOCTOR_AVAILABILITY TABLE
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('day_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('token_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slot_start_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('slot_end_time', sa.String(length=10), nullable=True))
        batch_op.drop_column('slot_end')
        batch_op.drop_column('slot_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_start', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('slot_end', sa.DATETIME(), nullable=False))
        batch_op.drop_column('slot_end_time')
        batch_op.drop_column('slot_start_time')
        batch_op.drop_column('token_number')
        batch_op.drop_column('day_name')
        batch_op.drop_column('slot_date')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_appointments_slot_id', type_='unique')
        batch_op.alter_column('cancellation_reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'COMPLETED', 'APPROVE', 'REJECT', name='appointmentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIRMED'"))
        batch_op.drop_column('booking_date')

    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('symptoms', sa.TEXT(), nullable=False),
    sa.Column('diagnosis', sa.TEXT(), nullable=False),
    sa.Column('prescription', sa.TEXT(), nullable=False),
    sa.Column('follow_up_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['old_appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    op.create_table('diagnostic_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('base_price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('old_appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('slot_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('token_number', sa.INTEGER(), nullable=False),
    sa.Column('cancellation_reason', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['diagnostic_services.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['old_doctor_availability.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_table('venues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('doctor_holidays')
    op.drop_table('doctor_configs')
    # ### end Alembic commands ###