"""add bio to doctor profile

Revision ID: 4b6c2d3e9587
Revises: 97af2d7e7ff1
Create Date: 2026-06-21 17:00:47.687575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6c2d3e9587'
down_revision = '97af2d7e7ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
