"""Added is_approved to doctor profile

Revision ID: 649c535989e1
Revises: 73e65235c023
Create Date: 2026-06-18 19:34:12.579161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649c535989e1'
down_revision = '73e65235c023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
