"""remove venue model and add venue_address

Revision ID: 6cde85fd4e92
Revises: 4b6c2d3e9587
Create Date: 2026-06-21 19:19:23.067279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cde85fd4e92'
down_revision = '4b6c2d3e9587'
branch_labels = None
depends_on = None


def upgrade():
    # 1. doctor_availability mein bina checking ke seedhe column add karein
    op.execute('ALTER TABLE doctor_availability ADD COLUMN venue_address VARCHAR(255);')
    
    # 2. doctor_profiles mein treatment_services column add karein
    op.execute('ALTER TABLE doctor_profiles ADD COLUMN treatment_services JSON;')

    # 3. Purane columns ko delete karne ke bajay chord dein (SQLite deadlock se bachne ke liye)
    # Note: Flask models se aapne 'venue_id' hata diya hai, isliye app sahi chalegi.
    pass



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_column('treatment_services')

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_home_visit', sa.BOOLEAN(), nullable=False))
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'])
        batch_op.drop_column('venue_address')

    # ### end Alembic commands ###
