"""add test deployment table

Revision ID: dcbf00949554
Revises: a4a81b59b9e6
Create Date: 2026-07-21 00:22:57.423262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbf00949554'
down_revision = 'a4a81b59b9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('token_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'COMPLETED', 'APPROVE', 'REJECT', name='appointmentstatus'), nullable=False))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['slot_id'])
        batch_op.create_foreign_key(None, 'doctor_profiles', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['member_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctor_availability', ['slot_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('day_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('token_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slot_start_time', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('slot_end_time', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('is_booked', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'doctor_profiles', ['doctor_id'], ['id'])
        batch_op.drop_column('start_time')

    with op.batch_alter_table('doctor_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('slot_duration_mins', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('work_on_sunday', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['doctor_id'])
        batch_op.create_foreign_key(None, 'doctor_profiles', ['doctor_id'], ['id'])

    with op.batch_alter_table('doctor_holidays', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor_profiles', ['doctor_id'], ['id'])

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False))
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('insurance_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_benefit', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('claim_window_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('validity_months', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('treatment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('venue_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('treatment_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['member_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])

    with op.batch_alter_table('reimbursement_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admin_remarks', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['medical_record_id'])
        batch_op.create_foreign_key(None, 'medical_records', ['medical_record_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_insurances', ['user_insurance_id'], ['id'])

    with op.batch_alter_table('user_insurances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('initial_coverage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('remaining_coverage', sa.Float(), nullable=False))
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.create_foreign_key(None, 'insurance_products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['member_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('user_insurances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.drop_column('remaining_coverage')
        batch_op.drop_column('initial_coverage')
        batch_op.drop_column('expiry_date')

    with op.batch_alter_table('reimbursement_claims', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('admin_remarks')
        batch_op.drop_column('status')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('treatment_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('venue_address')
        batch_op.drop_column('treatment_date')
        batch_op.drop_column('treatment_cost')

    with op.batch_alter_table('insurance_products', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('validity_months')
        batch_op.drop_column('claim_window_days')
        batch_op.drop_column('product_benefit')

    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_approved')
        batch_op.drop_column('treatment_services')
        batch_op.drop_column('bio')
        batch_op.drop_column('qualification')

    with op.batch_alter_table('doctor_holidays', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('doctor_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('work_on_sunday')
        batch_op.drop_column('fee')
        batch_op.drop_column('slot_duration_mins')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_booked')
        batch_op.drop_column('slot_end_time')
        batch_op.drop_column('slot_start_time')
        batch_op.drop_column('token_number')
        batch_op.drop_column('day_name')
        batch_op.drop_column('slot_date')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('token_number')
        batch_op.drop_column('booking_date')

    op.drop_table('test_deployment')
    # ### end Alembic commands ###
